version: '3.8'

services:

  ecom-mongo-dev:
    image: mongo
    container_name: ecom-mongo-dev
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEV_ROOT_USERNAME?Variable not set}
      MONGO_INITDB_ROOT_PASSWORD: ${DEV_ROOT_PASSWORD?Variable not set}
      MONGO_INITDB_DATABASE: dev-db
    volumes:
      - ecom-mongo-dev-data:/data/db
    networks:
      - ecom-dev-api-network

  ecom-mongo-express-dev:
    image: mongo-express
    container_name: ecom-mongo-express
    restart: unless-stopped
    env_file: .env
    ports:
      - "8181:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMINUSERNAME?Variable not set}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMINPASSWORD?Variable not set}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL?Variable not set}
    depends_on:
      - ecom-mongo-dev
    networks:
      - ecom-dev-api-network

  ecom-api:
    ports:
      - "8182:8000"
    env_file: .env
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    depends_on:
      - ecom-mongo-dev
    networks:
      - ecom-dev-api-network

volumes:
  ecom-mongo-dev-data:
    driver: local

networks:
  ecom-dev-api-network:

